### ISSUE TITLE
Eliminate double headings on element specs

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#39] opened 2022-07-25 22:37 UTC
The element specification pages have two identical headings. We don't know why. Putting this issue on Pat's radar in case it's a design issue. Assigning Martin in case it's a processing issue. 

See: [Element spec for ab](https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/lemdo_spec_ab.html)

**Comment by martindholmes** [comment] 2022-07-29 15:49
Fix committed in rev 9970. If all is well and the problem is gone, this can be closed.

**Comment by martindholmes** [comment] 2022-07-29 16:33
Fixed. Closing.

**Closed as completed by martindholmes** 2022-07-29 16:33 UTC
