### ISSUE TITLE
Display paragraph number and make it linkable in critical paratexts

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#46] opened 2022-08-16 22:22 UTC
We have added xml:ids to paragraphs in critical paratexts -- the ones that will be released relatively soon, although not in all the critical paratexts that are in the remediation queue.

Could we now display the paragraph number and make it linkable with a stable URL? 

Ask @Navarra-Houldin for examples if you need some.

**Comment by Navarra-Houldin** [comment] 2022-08-19 20:05
Could we also make `<div>`s linkable with stable URLs in critical paratexts? They have xml:ids.

**Comment by martindholmes** [comment] 2022-09-14 14:40
@Navarra-Houldin I think divs are already linkable aren't they? E.g. 

lemdo-dev/site/emdH5_GenIntro.html#emdH5_GenIntro_hauntedPlay

Do you mean that you would like to have the same clickable symbol next to the heading as we have in the documentation?

**Comment by Navarra-Houldin** [comment] 2022-09-14 17:29
@martindholmes Yes please. A clickable symbol should make navigation easier for users of the site.

**Comment by martindholmes** [comment] 2022-09-27 16:14
So, just to clarify the steps we need to take, and raise a couple of other questions:

1. Some critical paratexts now have paragraph ids of this form: ` xml:id="emdH5_GenIntro_p1"`. Where these occur, a number corresponding to the digit(s) following the _p should be placed in the margin, forming an anchor and a link. This will require that the text itself be moved to the right in order to accommodate the links, but there appears to be plenty of space for this. @pszpak should be invoked to go over the CSS after I've made this change.
2. Sections encoded as `<div>` elements also already have `@xml:id` attributes, and these should be used to create anchor/link structures using the pilcrow character: ¶ (U+00B6) as the first component of the heading, as we do in the documentation.

@Navarra-Houldin @JanelleJenstad Is this correct? Also, are there any implications for the PDFs here? I assume we don't want to add marginal paragraph numbers for the critical paratexts there, do we? It would be a bit awkward because the PDFs bring together many critical paratexts in a single document, and the numbering would restart from 1 with each new article, which might be confusing for the reader, but if we number them sequentially through the whole book, they will not match the numbers of the web versions.

**Comment by Navarra-Houldin** [comment] 2022-09-27 16:27
@martindholmes That all sounds correct to me. I agree that there shouldn't be any implications for the PDF - the goal is to make it easier to find and cite certain parts of the text, and the PDF already has page numbers to do that.

**Comment by martindholmes** [comment] 2022-10-06 16:45
`#2` is done in rev 10926.

**Comment by martindholmes** [comment] 2022-10-06 17:09
`#2` is done in rev 10928.

Leaving this ticket open so we can confirm that the build looks/works as intended.

**Comment by martindholmes** [comment] 2022-10-12 23:17
Closing this.

**Closed as completed by martindholmes** 2022-10-12 23:17 UTC
Labels: enhancement, go for it, fix committed
