### ISSUE TITLE
Write handling for figure descriptions in PDF output

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#49] opened 2022-08-18 21:41 UTC
For the first time, we have added an image to an edition in a file destined for both HTML and PDF outputs. 

The HTML output is reasonably good (although we'll want Pat to tweak it). See [emdH5_GenIntro](https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/emdH5_GenIntro.html). 

But the PDF is putting the contents of `figDesc` at the top of the next paragraph. See p. v and vi of the PDF of Henry V.

**Comment by martindholmes** [comment] 2022-09-01 22:48
Initial fix added in rev 10847, but there's more to do. The caption now renders under the image and does not appear in the regular text flow, but the addition of the caption now overflows the intended print area and I think I need to constrain the image size when a caption exists. The problem is that the change in image size is going to have to be controlled by the size of the caption, which is impossible to know at build time. So we might end up with some compromises here.

**Comment by martindholmes** [comment] 2022-09-02 19:54
I think this is now working; I've added a sizing component to make room for the caption on the page. Closing.

**Closed as completed by martindholmes** 2022-09-02 19:54 UTC
Labels: bug, in progress
