### ISSUE TITLE
Fix rendering of speech numbers in Prologues

### ISSUE THREAD

**Issue by JanelleJenstad** [projectLEMDO/lemdoIssues#27] opened 2022-06-27 18:14 UTC
Related to issue #28. One fix might do for both issues.

In the sp numbering system in the online texts, Prol.1 speech doesn’t have the appropriate text bearing the link. It's coming up as simply "link." Can we make it Prol.1 or Prologue 1?

For example, see [(https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/emdSel_M.html#emdSel_M_prologue_sp1)](https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/emdSel_M.html#emdSel_M_prologue_sp1)

If the challenge is that these things are unpredictable, let's talk about how to make them more predictable.

**Comment by martindholmes** [comment] 2022-06-28 22:40
The emdSel_M file is not encoded properly. We  have a protocol for ASSP:

~~~~~
a = act, s = scene, sp = speech, f = figure, p = para, ps = epilogue etc., pr = prologue etc.. -->
    <xsl:variable name="asspRegex" as="xs:string">(_((a)|(s)|(sp)|(p)|(pr)|(ps)|(f))\d+)+$</xsl:variable>
~~~~~

For prologue/epilogue type things, we detect the "pr" or "ps" and then look at the `@n` value on the element to retrieve the correct expansion. We worked this out in great detail, and the units are documented here:

lemdo-dev/site/learn_stableEntities.html

However, that page seems to have invented a new unit which was never in the plan and which I don't remember ever hearing about, "bt". 

I'm going to close this ticket because as far as I can see, the problem is simply broken encoding, and there don't appear to be any texts actually using the "bt" thing so I don't think we need to complicate things further until it's actually required, in which case we'll have an actual text to work with in testing.

**Closed as completed by martindholmes** 2022-06-28 22:40 UTC
Labels: bug

**Comment by JanelleJenstad** [comment] 2022-06-28 22:56
D'oh! Yes, of course it's wrongly encoded. I will fix that right now. 

"bt" is for "between". Some plays have entre-actes and speeches between scenes (e.g., plays by Ben Jonson). We talked about it extensively in team meetings in 2021. The documentation is here: [https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/learn_intraText.html](https://jenkins.hcmc.uvic.ca/job/LEMDO/lastSuccessfulBuild/artifact/products/lemdo-dev/site/learn_intraText.html).
